{{- $webapp := .Values.georchestra.webapps.openldap -}}
{{- $webapp_storage := .Values.georchestra.storage.openldap_config -}}
{{- if $webapp.enabled -}}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "georchestra.fullname" . }}-openldap-config
  labels:
    {{- include "georchestra.labels" . | nindent 4 }}
    app.kubernetes.io/component: {{ include "georchestra.fullname" . }}-ldap
    helm.sh/resource-policy: "keep"
spec:
  accessModes:
  - ReadWriteOnce
  {{- if .Values.georchestra.storage.openldap_config.storage_class_name }}
  storageClassName: {{ .Values.georchestra.storage.openldap_config.storage_class_name }}
  {{- else if .Values.georchestra.storage.storage_class_name }}
  storageClassName: {{ .Values.georchestra.storage.storage_class_name }}
  {{- end }}
  {{- if .Values.georchestra.storage.openldap_config.pv_name }}
  volumeName: {{ .Values.georchestra.storage.openldap_config.pv_name }}
  {{- end }}
  resources:
    requests:
      storage: {{ .Values.georchestra.storage.openldap_config.size }}
{{- end }}
