{{- $webapp := .Values.georchestra.datadirsync  -}}
{{- if $webapp.enabled -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "georchestra.fullname" . }}-datadirsync-credentials
type: Opaque
data:
  username: {{ .Values.gitCredentials.username | b64enc }}
  token: {{ .Values.gitCredentials.token | b64enc }}
  ssh: {{ .Values.gitCredentials.ssh | b64enc }}
{{- end }}
