{{- $webapp := .Values.georchestra.datadirsync  -}}
{{- if $webapp.enabled -}}
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ include "georchestra.fullname" . }}-datadirsync-rolebinding
subjects:
  - kind: ServiceAccount
    name: {{ include "georchestra.fullname" . }}-datadirsync-serviceaccount
    namespace: {{ .Release.Namespace }}
roleRef:
  kind: Role
  name: {{ include "georchestra.fullname" . }}-datadirsync-role
  apiGroup: rbac.authorization.k8s.io
{{- end }}