{{- $webapp := .Values.georchestra.datadirsync -}}
{{- if $webapp.enabled -}}
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: {{ .Release.Namespace }}
  name: {{ include "georchestra.fullname" . }}-datadirsync-role
rules:
  - apiGroups: ["apps"]
    resources: ["pods", "replicasets", "deployments"]
    resourceNames: [{{- $prefix := include "georchestra.fullname" . -}}
      {{- $suffixes := $webapp.deploymentSuffixNameList -}}
      {{- $deployments := list -}}
      {{- range $index, $suffix := $suffixes }}
      {{ if $index }}, {{ end }}"{{ printf "%s-%s" $prefix $suffix }}"
      {{- end }}]
    verbs: ["get", "patch"]
{{- end }}