{{- $rabbitmq := .Values.rabbitmq -}}
{{- if $rabbitmq.enabled -}}
{{- if not $rabbitmq.auth.existingSecret -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "georchestra.fullname" . }}-rabbitmq-georchestra-secret
  labels:
    {{- include "georchestra.labels" . | nindent 4 }}
type: Opaque
data:
  {{- if $rabbitmq.builtin }}
  host: {{ printf "%s-rabbitmq" .Release.Name | b64enc | quote  }}
  {{- else }}
  host: {{ $rabbitmq.auth.host | b64enc | quote }}
  {{- end }}
  password: {{ $rabbitmq.auth.password | b64enc | quote }}
  port: {{ $rabbitmq.auth.port | b64enc | quote }}
  user: {{ $rabbitmq.auth.username | b64enc | quote }}
{{- end }}
{{- end }}
