{{- $rabbitmq := .Values.rabbitmq -}}
{{- $rabbitmq_storage := .Values.rabbitmq.storage -}}
{{- if and $rabbitmq.enabled (not $rabbitmq.auth.host) -}}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "georchestra.fullname" . }}-rabbitmq
  {{- with $rabbitmq_storage.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  labels:
    {{- include "georchestra.labels" . | nindent 4 }}
    app.kubernetes.io/component: {{ include "georchestra.fullname" . }}-rabbitmq
    {{- with $rabbitmq_storage.labels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
spec:
  accessModes:
  {{- if $rabbitmq_storage.accessModes }}
  {{- range $rabbitmq_storage.accessModes }}
  - {{ . | quote }}
  {{- end }}
  {{- else }}
  - "ReadWriteOnce"
  {{- end }}
  {{- if (eq "-" $rabbitmq_storage.storage_class_name) }}
  storageClassName: ""
  {{- else if $rabbitmq_storage.storage_class_name }}
  storageClassName: {{ $rabbitmq_storage.storage_class_name }}
  {{- end }}
  {{- if $rabbitmq_storage.pv_name }}
  volumeName: {{ $rabbitmq_storage.pv_name }}
  {{- end }}
  resources:
    requests:
      storage: {{ $rabbitmq_storage.size }}
{{- end }}
