{{- $webapp := .Values.georchestra.webapps.geonetwork -}}
{{- if and $webapp.enabled $webapp.housekeeping.harvester_logs.enabled -}}
apiVersion: batch/v1
kind: CronJob
metadata:
  name: {{ include "georchestra.fullname" . }}-housekeeping-clean-harvester-logs
  labels:
    {{- include "georchestra.labels" . | nindent 4 }}
    app.kubernetes.io/component: {{ include "georchestra.fullname" . }}-housekeeping-clean-harvester-logs
spec:
  schedule: "{{ $webapp.housekeeping.harvester_logs.schedule }}"
  jobTemplate:
    spec:
      ttlSecondsAfterFinished: 86400
      template:
        spec:
          containers:
          - name: clean-harvester-logs
            image: busybox:latest
            imagePullPolicy: IfNotPresent
            command:
            - find
            - /mnt/geonetwork_datadir/harvester_logs/
            - -name
            - harvester_*.log
            - -mtime
            - '+1'
            - -delete
            volumeMounts:
            - mountPath: /mnt/geonetwork_datadir
              name: geonetwork-datadir
            resources:
              {{- toYaml $webapp.resources | nindent 14 }}
          volumes:
          - name: geonetwork-datadir
            persistentVolumeClaim:
              claimName: {{ include "georchestra.fullname" . }}-geonetwork-datadir
          restartPolicy: OnFailure
          {{- if $webapp.housekeeping.tolerations }}
          tolerations:
            {{- $webapp.housekeeping.tolerations | toYaml | nindent 12}}
          {{- end }}
{{- end -}}
