{{- $redis := .Values.redis -}}
{{- if $redis.enabled -}}
{{- if not $redis.auth.existingSecret -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "georchestra.fullname" . }}-redis-georchestra-secret
  labels:
    {{- include "georchestra.labels" . | nindent 4 }}
type: Opaque
data:
  {{- if not $redis.auth.host }}
  host: {{ printf "%s-redis" (include "georchestra.fullname" .) | b64enc | quote  }}
  {{- else }}
  host: {{ $redis.auth.host | b64enc | quote }}
  {{- end }}
  port: {{ $redis.auth.port | b64enc | quote }}
  password: {{ $redis.auth.password | b64enc | quote }}
{{- end }}
{{- end }}
