{{- if .Values.georchestra.webapps.gateway.enabled -}}
{{- $webapp := .Values.georchestra.webapps.gateway -}}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "georchestra.fullname" . }}-gateway
  labels:
    {{- include "georchestra.labels" . | nindent 4 }}
    app.kubernetes.io/component: {{ include "georchestra.fullname" . }}-gateway
spec:
  replicas: 1
  selector:
    matchLabels:
      {{- include "georchestra.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: {{ include "georchestra.fullname" . }}-gateway
  template:
    metadata:
      labels:
        {{- include "georchestra.selectorLabels" . | nindent 8 }}
        org.georchestra.service/name: {{ include "georchestra.fullname" . }}-gateway
        app.kubernetes.io/component: {{ include "georchestra.fullname" . }}-gateway
    spec:
      nodeSelector:
        "kubernetes.io/os": linux
      initContainers:
      {{ include "georchestra.bootstrap_georchestra_datadir" . | nindent 6 }}
      containers:
      - name: georchestra-gateway
        image: {{ $webapp.docker_image }}
        imagePullPolicy: Always
        env:
          - name: ANALYTICS_HOST
            value: "{{ include "georchestra.fullname" . }}-analytics-svc"
          - name: ATLAS_HOST
            value: "{{ include "georchestra.fullname" . }}-atlas-svc"
          - name: CAS_HOST
            value: "{{ include "georchestra.fullname" . }}-cas-svc"
          - name: CONSOLE_HOST
            value: "{{ include "georchestra.fullname" . }}-console-svc"
          - name: EXTRACTORAPP_HOST
            value: "{{ include "georchestra.fullname" . }}-extractorapp-svc"
          - name: GEONETWORK_HOST
            value: "{{ include "georchestra.fullname" . }}-geonetwork-svc"
          - name: GEOSERVER_HOST
            value: "{{ include "georchestra.fullname" . }}-geoserver-svc"
          - name: HEADER_HOST
            value: "{{ include "georchestra.fullname" . }}-header-svc"
          - name: MAPFISHAPP_HOST
            value: "{{ include "georchestra.fullname" . }}-mapfishapp-svc"
          - name: GEOWEBCACHE_HOST
            value: "{{ include "georchestra.fullname" . }}-geowebcache-svc"
          - name: MAPSTORE_HOST
            value: "{{ include "georchestra.fullname" . }}-mapstore-svc"
          - name: DATAFEEDER_HOST
            value: "{{ include "georchestra.fullname" . }}-datafeeder-svc"
          - name: IMPORT_HOST
            value: "{{ include "georchestra.fullname" . }}-import-svc"          
          - name: JAVA_TOOL_OPTIONS
            value: "-Dgeorchestra.datadir=/etc/georchestra -Dspring.profiles.active=docker"
          {{- include "georchestra.common-envs" . | nindent 10 }}
          {{- include "georchestra.ldap-envs" . | nindent 10 }}
          {{- include "georchestra.database-georchestra-envs" . | nindent 10 }}
          {{- if $webapp.extra_environment }}
          {{- $webapp.extra_environment | toYaml | nindent 10 }}
          {{- end }}
        ports:
        - containerPort: 8080
          name: gateway
        volumeMounts:
          - mountPath: /etc/georchestra
            name: georchestra-datadir
        livenessProbe:
          httpGet:
            path: /actuator/health
            port: 8090
          periodSeconds: 10
          timeoutSeconds: 3
        startupProbe:
          tcpSocket:
            port: 8080
          failureThreshold: 5
          periodSeconds: 15
      volumes:
      - name: georchestra-datadir
        emptyDir: {}
      {{- if .Values.georchestra.datadir.git.ssh_secret }}
      - name: ssh-secret
        secret:
          secretName: {{ .Values.georchestra.datadir.git.ssh_secret }}
          defaultMode: 0400
      {{- end }}
      {{- if $webapp.registry_secret }}
      imagePullSecrets:
      - name: {{ $webapp.registry_secret }}
      {{- end }}
{{- end }}
