{{- if .Values.gaiaCelery.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "helm-gaia.fullname" . }}-gaia-celery-svc
  labels:
    {{- include "helm-gaia.labels" . | nindent 4 }}
  {{- with .Values.gaiaCelery.service.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  type: {{ .Values.gaiaCelery.service.type }}
  ports:
    - port: {{ .Values.gaiaCelery.service.port }}
      targetPort: http
      protocol: TCP
  selector:
    {{- include "helm-gaia.selectorLabelsCelery" . | nindent 4 }}
{{- end }}
