apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "helm-gaia.fullname" . }}-redis-data
  labels:
    {{- include "helm-gaia.labels" . | nindent 4 }}
    app.kubernetes.io/component: {{ include "helm-gaia.fullname" . }}-redis-data
    helm.sh/resource-policy: "keep"
spec:
  accessModes:
  {{- if.Values.redis.redisData.accessModes }}
  {{- range .Values.redis.redisData.accessModes }}
  - {{ . | quote }}
  {{- end }}
  {{- else }}
  {{- range .Values.redis.redisData.accessModes }}
  - {{ . | quote }}
  {{- end }}
  {{- end }}
  {{- if (eq "-" .Values.redis.redisData.storageClassName) }}
  storageClassName: ""
  {{- else if .Values.redis.redisData.storageClassName }}
  storageClassName: {{ .Values.redis.redisData.storageClassName }}
  {{- else if (eq "-" .Values.redis.redisData.storageClassName) }}
  storageClassName: ""
  {{- else if .Values.redis.redisData.storageClassName }}
  storageClassName: {{ .Values.redis.redisData.storageClassName }}
  {{- end }}
  {{- if .Values.redis.redisData.pvName }}
  volumeName: {{ .Values.redis.redisData.pvName }}
  {{- end }}
  resources:
    requests:
      storage: {{ .Values.redis.redisData.size }}
