{{- if .Values.redis.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "helm-gaia.fullname" . }}-gaia-redis-svc
  labels:
    {{- include "helm-gaia.labels" . | nindent 4 }}
spec:
  type: {{ .Values.redis.service.type }}
  ports:
    - port: {{ .Values.redis.service.port }}
      targetPort: redis
      protocol: TCP
  selector:
    {{- include "helm-gaia.selectorLabelsRedis" . | nindent 4 }}
{{- end }}
