{{- if and .Values.georchestra.webapps.datafeeder.enabled .Values.georchestra.webapps.datafeeder_frontend.enabled -}}
{{- $webapp := .Values.georchestra.webapps.datafeeder_frontend -}}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "georchestra.fullname" . }}-import
  labels:
    {{- include "georchestra.labels" . | nindent 4 }}
    app.kubernetes.io/component: {{ include "georchestra.fullname" . }}-datafeeder-import
spec:
  replicas: 1
  selector:
    matchLabels:
      {{- include "georchestra.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: {{ include "georchestra.fullname" . }}-datafeeder-import
  template:
    metadata:
      labels:
        {{- include "georchestra.selectorLabels" . | nindent 8 }}
        org.georchestra.service/name: {{ include "georchestra.fullname" . }}-import
        app.kubernetes.io/component: {{ include "georchestra.fullname" . }}-datafeeder-import
    spec:
      nodeSelector:
        "kubernetes.io/os": linux
      containers:
      - name: georchestra-import
        image: {{ $webapp.docker_image }}
        imagePullPolicy: Always
        ports:
        - containerPort: 80
          name: http
        livenessProbe:
          httpGet:
            path: /index.html
            port: 80
          periodSeconds: 10
          timeoutSeconds: 5
        startupProbe:
          tcpSocket:
            port: 80
          failureThreshold: 5
          periodSeconds: 5
      {{- if $webapp.registry_secret }}
      imagePullSecrets:
      - name: {{ $webapp.registry_secret }}
      {{- end }}
{{- end }}
