{{- if and (.Values.database.datafeeder)  (not .Values.database.datafeeder.auth.existingSecret) }}
{{- $database := .Values.database.datafeeder -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "georchestra.fullname" . }}-database-datafeeder-secret
  labels:
    {{- include "georchestra.labels" . | nindent 4 }}
type: Opaque
data:
  dbname: {{ required ".Values.datafeeder.auth.dbname is required." $database.auth.database | b64enc | quote }}
  host: {{ required ".Values.datafeeder.auth.host is required." $database.auth.host | b64enc | quote }}
  password: {{ required ".Values.datafeeder.auth.password is required." $database.auth.password | b64enc | quote }}
  port: {{ required ".Values.datafeeder.auth.port is required." $database.auth.port | b64enc | quote }}
  user: {{ required ".Values.datafeeder.auth.username is required." $database.auth.username | b64enc | quote }}
{{- end }}
