{{- if .Values.rabbitmq.enabled and .Values.rabbitmq.storage -}}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "georchestra.fullname" . }}-rabbitmq
  labels:
    {{- include "georchestra.labels" . | nindent 4 }}
    app.kubernetes.io/component: {{ include "georchestra.fullname" . }}-rabbitmq
spec:
  accessModes:
  - ReadWriteOnce
  {{- if .Values.rabbitmq.storage.storage_class_name }}
  storageClassName: {{ .Values.rabbitmq.storage.storage_class_name }}
  {{- end }}
  {{- if .Values.rabbitmq.storage.pv_name }}
  volumeName: {{ .Values.rabbitmq.storage.pv_name }}
  {{- end }}
  resources:
    requests:
      storage: {{ .Values.rabbitmq.storage.size }}
{{- end }}