{{- $webapp := .Values.backend -}}
{{- if $webapp.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "datafeeder-python.fullname" . }}-backend
  labels:
    {{- include "datafeeder-python.labels" . | nindent 4 }}
spec:
  replicas: {{ $webapp.replicaCount | default 2 }}
  selector:
    matchLabels:
      {{- include "datafeeder-python.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: {{ include "datafeeder-python.fullname" . }}-backend
  template:
    metadata:
      {{- with $webapp.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "datafeeder-python.selectorLabels" . | nindent 8 }}
        app.kubernetes.io/component: {{ include "datafeeder-python.fullname" . }}-backend
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      securityContext:
        {{- toYaml $webapp.podSecurityContext | nindent 8 }}
      {{- with $webapp.nodeSelector }}
      nodeSelector:
        {{- toYaml . |nindent 8 }}
      {{- end }}
      {{- with $webapp.affinity }}
      affinity:
        {{- toYaml . |nindent 8 }}
      {{- end }}
      {{- with $webapp.tolerations }}
      tolerations:
        {{- toYaml . |nindent 8 }}
      {{- end }}
      initContainers:
      {{ include "georchestra.bootstrap_georchestra_datadir" . | nindent 6 }}
      containers:
      - name: backend
        image: "{{ $webapp.image.repository }}:{{ $webapp.image.tag }}"
        imagePullPolicy: {{ $webapp.image.imagePullPolicy }}
        ports:
        - name: http
          containerPort: 8000
          protocol: TCP
        env:
          {{- include "datafeeder-python.database-envs" . | nindent 10 }}
          {{- include "datafeeder-python.data-database-envs" . | nindent 10 }}
          - name: DATADIR
            value: "/etc/georchestra"
          - name: ENVIRONMENT
            value: "production"
          - name: BACKEND_URL
            value: "http://{{ include "datafeeder-python.fullname" . }}-backend-svc:8000"
          - name: FRONTEND_HOST
            value: "{{ $webapp.config.frontend.url }}"
          - name: BACKEND_CORS_ORIGINS
            value: "{{ $webapp.config.corsOrigins }}"
          - name: CONSOLE_URL
            value: "{{ $webapp.config.console.url | default "http://georchestra-console-svc:8080/console" }}"
          - name: GEOSERVER_URL
            value: "{{ $webapp.config.geoserver.url | default "http://georchestra-gateway-svc:8080/geoserver" }}"
          - name: GEOSERVER_USER
            value: "{{ $webapp.config.geoserver.username }}"
          - name: GEOSERVER_PASSWORD
            value: "{{ $webapp.config.geoserver.password }}"
          - name: GEONETWORK_URL
            value: "{{ $webapp.config.geonetwork.url | default "http://georchestra-gateway-svc:8080/geonetwork" }}"
          - name: GEONETWORK_USERNAME
            value: "{{ $webapp.config.geonetwork.username }}"
          - name: GEONETWORK_PASSWORD
            value: "{{ $webapp.config.geonetwork.password }}"
          - name: AIRFLOW_URL
            value: {{ $webapp.config.airflow.url | default (printf "http://%s-api-server:8080/airflow" .Release.Name) | quote }}
          - name: AIRFLOW_USERNAME
            value: "{{ $webapp.config.airflow.username }}"
          - name: AIRFLOW_PASSWORD
            value: "{{ $webapp.config.airflow.password }}"
          - name: METADATA_FETCH_GROUPS_URL
            value: "{{ $webapp.config.metadataFetchGroupsUrl | default "http://georchestra-console-svc:8080/console/internal/organizations" }}"
          - name: DATA_FETCH_GROUPS_URL
            value: "{{ $webapp.config.dataFetchGroupsUrl | default "http://georchestra-console-svc:8080/console/internal/roles" }}"
            {{- with $webapp.extraEnv }}
              {{- toYaml . | nindent 10 }}
            {{- end }}
        envFrom:
          - secretRef:
              name: {{ include "datafeeder-python.fullname" . }}-backend
        resources:
          {{- toYaml $webapp.resources | nindent 10 }}
        securityContext:
          {{- toYaml $webapp.securityContext | nindent 12 }}
        {{- with $webapp.lifecycle }}
        lifecycle:
          {{- toYaml . | nindent 10 }}
        {{- end }}
        volumeMounts:
          - mountPath: /etc/georchestra
            name: georchestra-datadir
          - mountPath: /tmpbackend
            name: temp-backend
        {{- if $webapp.extraVolumeMounts }}
          {{- $webapp.extraVolumeMounts | toYaml | nindent 8 }}
        {{- end }}
      volumes:
      - name: georchestra-datadir
        emptyDir: {}
      - name: temp-backend
        emptyDir: {}
      {{- if .Values.backend.datadir.git.ssh_secret }}
      - name: ssh-secret
        secret:
          secretName: {{ .Values.backend.datadir.git.ssh_secret }}
          defaultMode: 0400
      {{- end }}
      {{- if $webapp.extraVolumes }}
        {{ $webapp.extraVolumes | toYaml | nindent 6 }}
      {{- end }}
{{- end }}
