{{- $webapp := .Values.georchestra.webapps.geonetwork.kibana -}}
{{- if .Values.georchestra.webapps.geonetwork.enabled -}}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "georchestra.fullname" . }}-gn4-kibana-svc
  labels:
    {{- include "georchestra.labels" . | nindent 4 }}
    app.kubernetes.io/component: {{ include "georchestra.fullname" . }}-gn4-kibana
  {{- with $webapp.service.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  ports:
  - port: 5601
    protocol: TCP
    targetPort: 5601
  selector:
    org.georchestra.service/name: {{ include "georchestra.fullname" . }}-gn4-kibana
{{- end }}