{{- $webapp := .Values.georchestra.webapps.openldap -}}
{{- if $webapp.enabled -}}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "georchestra.fullname" . }}-ldap-svc
  labels:
    {{- include "georchestra.labels" . | nindent 4 }}
    app.kubernetes.io/component: {{ include "georchestra.fullname" . }}-ldap
  {{- with $webapp.service.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  ports:
  - port: 389
    protocol: TCP
    targetPort: 389
  selector:
    org.georchestra.service/name: {{ include "georchestra.fullname" . }}-ldap
{{- end }}
