{{- if (not .Values.ldap.existingSecret ) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "georchestra.fullname" . }}-ldap-passwords-secret
  labels:
    {{- include "georchestra.labels" . | nindent 4 }}
type: Opaque
data:
  SLAPD_PASSWORD: {{ .Values.ldap.adminPassword | b64enc | quote }}
{{- end }}
