{{- if .Values.georchestra.webapps.geonetwork.enabled -}}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "georchestra.fullname" . }}-gn4-es-data
  labels:
    {{- include "georchestra.labels" . | nindent 4 }}
    app.kubernetes.io/component: {{ include "georchestra.fullname" . }}-gn4-elasticsearch
spec:
  accessModes:
  - ReadWriteOnce
  {{- if .Values.georchestra.storage.storage_class_name }}
  storageClassName: {{ .Values.georchestra.storage.storage_class_name }}
  {{- end }}
  {{- if .Values.georchestra.storage.gn4_es.pv_name }}
  volumeName: {{ .Values.georchestra.storage.gn4_es.pv_name }}
  {{- end }}
  resources:
    requests:
      storage: {{ .Values.georchestra.storage.gn4_es.size }}
{{- end }}