{{- $webapp := .Values.georchestra.webapps.geonetwork.elasticsearch -}}
{{- $webapp_storage := .Values.georchestra.storage.gn4_es -}}
{{- if $webapp.enabled -}}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "georchestra.fullname" . }}-gn4-es-data
  labels:
    {{- include "georchestra.labels" . | nindent 4 }}
    app.kubernetes.io/component: {{ include "georchestra.fullname" . }}-gn4-elasticsearch
    helm.sh/resource-policy: "keep"
spec:
  accessModes:
  - ReadWriteOnce
  {{- if $webapp_storage.storage_class_name }}
  storageClassName: {{ $webapp_storage.storage_class_name }}
  {{- else if .Values.georchestra.storage.storage_class_name }}
  storageClassName: {{ .Values.georchestra.storage.storage_class_name }}
  {{- end }}
  {{- if $webapp_storage.pv_name }}
  volumeName: {{ $webapp_storage.pv_name }}
  {{- end }}
  resources:
    requests:
      storage: {{ $webapp_storage.size }}
{{- end }}