{{- if .Values.georchestra.webapps.geonetwork.enabled -}}
{{- $webapp := .Values.georchestra.webapps.geonetwork -}}
{{- $database := .Values.database -}}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "georchestra.fullname" . }}-geonetwork
  labels:
    {{- include "georchestra.labels" . | nindent 4 }}
    app.kubernetes.io/component: {{ include "georchestra.fullname" . }}-geonetwork
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      {{- include "georchestra.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: {{ include "georchestra.fullname" . }}-geonetwork
  template:
    metadata:
      labels:
        {{- include "georchestra.selectorLabels" . | nindent 8 }}
        org.georchestra.service/name: {{ include "georchestra.fullname" . }}-geonetwork
        app.kubernetes.io/component: {{ include "georchestra.fullname" . }}-geonetwork
      {{- if $webapp.jetty_monitoring }}
      annotations:
        prometheus.io/path: /metrics
        prometheus.io/port: "9103"
        prometheus.io/scrape: "true"
      {{- end }}
    spec:
      nodeSelector:
        "kubernetes.io/os": linux
      securityContext:
        fsGroup: 999
      initContainers:
      {{ include "georchestra.bootstrap_georchestra_datadir" $ | nindent 6 }}
      - name: fix-permissions-pvc
        image: busybox:latest
        command: ["sh", "-c", "chown -R 999:999 /mnt/geonetwork_datadir"]   
        volumeMounts:
        - mountPath: /mnt/geonetwork_datadir
          name: geonetwork-datadir
      containers:
      - name: georchestra-geonetwork
        image: {{ $webapp.docker_image }}
        imagePullPolicy: Always
        volumeMounts:
          - mountPath: /etc/georchestra
            name: georchestra-datadir
          - mountPath: /mnt/geonetwork_datadir
            name: geonetwork-datadir
        {{- if $webapp.extra_volumeMounts }}
          {{ $webapp.extra_volumeMounts | toYaml | nindent 10 }}
        {{- end }}
        ports:
        - containerPort: 8080
          name: http-proxy
        env:
        - name: GEORCHESTRA_CONSOLE_URL
          value: "{{ include "georchestra.fullname" . }}-console-svc"
        - name: ES_FEATUREPROXY_TARGETURI
          value: "{{ include "georchestra.fullname" . }}-gn4-kibana-svc"
        - name: KB_URL
          value: "{{ include "georchestra.fullname" . }}-gn4-kibana-svc"
          {{- include "georchestra.database-georchestra-envs" . | nindent 8 }}
          {{- if $webapp.extra_environment }}
          {{- $webapp.extra_environment | toYaml | nindent 8 }}
          {{- end }}
        livenessProbe:
          httpGet:
            path: /geonetwork/srv/eng/catalog.search
            port: 8080
          periodSeconds: 10
          timeoutSeconds: 5
        startupProbe:
          tcpSocket:
            port: 8080
          failureThreshold: 5
          periodSeconds: 50
      {{- if $webapp.jetty_monitoring }}
      - name: jmx-collectd
        image: camptocamp/jmx-collectd:bullseye
        volumeMounts:
        - mountPath: /collectd-template
          name: georchestra-monitoring-cm
        ports:
        - containerPort: 9103
          name: prometheus
        command:
        - /bin/sh
        - -c
        - mkdir /etc/collectd/collectd.conf.d/ ;
          cat /collectd-template/collectd-jmx-jetty.conf | sed "s/localhost/$(hostname)/g" > /etc/collectd/collectd.conf.d/jmx.conf ;
          collectd -f
      {{- end }}
      volumes:
      - name: georchestra-datadir
        emptyDir: {}
      - name: geonetwork-datadir
        persistentVolumeClaim:
          claimName: {{ include "georchestra.fullname" . }}-geonetwork-datadir
      {{- if .Values.georchestra.datadir.git.ssh_secret }}
      - name: ssh-secret
        secret:
          secretName: {{ .Values.georchestra.datadir.git.ssh_secret }}
          defaultMode: 0400
      {{- end }}
      {{- if $webapp.extra_volumes }}
          {{ $webapp.extra_volumes | toYaml | nindent 6 }}
      {{- end }}
      {{- if $webapp.jetty_monitoring }}
      - name: georchestra-monitoring-cm
        configMap:
          name: {{ include "georchestra.fullname" . }}-monitoring-cm
      {{- end }}
      {{- if $webapp.registry_secret }}
      imagePullSecrets:
      - name: {{ $webapp.registry_secret }}
      {{- end }}
{{- end }}