{{- if .Values.georchestra.webapps.proxy.enabled -}}
{{- $webapp := .Values.georchestra.webapps.proxy -}}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "georchestra.fullname" . }}-sp
  labels:
    {{- include "georchestra.labels" . | nindent 4 }}
    app.kubernetes.io/component: {{ include "georchestra.fullname" . }}-sp
spec:
  replicas: 1
  selector:
    matchLabels:
      {{- include "georchestra.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: {{ include "georchestra.fullname" . }}-sp
  template:
    metadata:
      labels:
        {{- include "georchestra.selectorLabels" . | nindent 8 }}
        org.georchestra.service/name: {{ include "georchestra.fullname" . }}-sp
        app.kubernetes.io/component: {{ include "georchestra.fullname" . }}-sp

      {{- if $webapp.jetty_monitoring }}
      annotations:
        prometheus.io/path: /metrics
        prometheus.io/port: "9103"
        prometheus.io/scrape: "true"
      {{- end }}
    spec:
      nodeSelector:
        "kubernetes.io/os": linux
      initContainers:
      {{ include "georchestra.bootstrap_georchestra_datadir" . | nindent 6 }}
      {{- if .Values.georchestra.webapps.proxy.envsubst.enabled }}
      - name: envsubst
        image: georchestra/k8s-initcontainer-envsubst
        volumeMounts:
        - mountPath: /etc/georchestra
          name: georchestra-datadir
        env:
        - name: DEBUG
          value: "yes"
        - name: SUBST_FILES
          value: "/etc/georchestra/security-proxy/targets-mapping.properties"
        - name: ANALYTICS_HOST
          value: "{{ include "georchestra.fullname" . }}-analytics-svc"
        - name: ATLAS_HOST
          value: "{{ include "georchestra.fullname" . }}-atlas-svc"
        - name: CAS_HOST
          value: "{{ include "georchestra.fullname" . }}-cas-svc"
        - name: CONSOLE_HOST
          value: "{{ include "georchestra.fullname" . }}-console-svc"
        - name: EXTRACTORAPP_HOST
          value: "{{ include "georchestra.fullname" . }}-extractorapp-svc"
        - name: GEONETWORK_HOST
          value: "{{ include "georchestra.fullname" . }}-geonetwork-svc"
        - name: GEOSERVER_HOST
          value: "{{ include "georchestra.fullname" . }}-geoserver-svc"
        - name: HEADER_HOST
          value: "{{ include "georchestra.fullname" . }}-header-svc"
        - name: MAPFISHAPP_HOST
          value: "{{ include "georchestra.fullname" . }}-mapfishapp-svc"
        - name: GEOWEBCACHE_HOST
          value: "{{ include "georchestra.fullname" . }}-geowebcache-svc"
        - name: MAPSTORE_HOST
          value: "{{ include "georchestra.fullname" . }}-mapstore-svc"
        - name: DATAFEEDER_HOST
          value: "{{ include "georchestra.fullname" . }}-datafeeder-svc"
        - name: IMPORT_HOST
          value: "{{ include "georchestra.fullname" . }}-import-svc"
        - name: OGCAPIRECORDS_HOST
          value: "{{ include "georchestra.fullname" . }}-gn4-ogc-api-records-svc"
      {{- end }}
      containers:
      - name: georchestra-sp
        image: {{ $webapp.docker_image }}
        imagePullPolicy: Always
        env:
        - name: ANALYTICS_HOST
          value: "{{ include "georchestra.fullname" . }}-analytics-svc"
        - name: ATLAS_HOST
          value: "{{ include "georchestra.fullname" . }}-atlas-svc"
        - name: CAS_HOST
          value: "{{ include "georchestra.fullname" . }}-cas-svc"
        - name: CONSOLE_HOST
          value: "{{ include "georchestra.fullname" . }}-console-svc"
        - name: EXTRACTORAPP_HOST
          value: "{{ include "georchestra.fullname" . }}-extractorapp-svc"
        - name: GEONETWORK_HOST
          value: "{{ include "georchestra.fullname" . }}-geonetwork-svc"
        - name: GEOSERVER_HOST
          value: "{{ include "georchestra.fullname" . }}-geoserver-svc"
        - name: HEADER_HOST
          value: "{{ include "georchestra.fullname" . }}-header-svc"
        - name: MAPFISHAPP_HOST
          value: "{{ include "georchestra.fullname" . }}-mapfishapp-svc"
        - name: GEOWEBCACHE_HOST
          value: "{{ include "georchestra.fullname" . }}-geowebcache-svc"
        - name: MAPSTORE_HOST
          value: "{{ include "georchestra.fullname" . }}-mapstore-svc"
        - name: DATAFEEDER_HOST
          value: "{{ include "georchestra.fullname" . }}-datafeeder-svc"
        - name: IMPORT_HOST
          value: "{{ include "georchestra.fullname" . }}-import-svc"
          {{- include "georchestra.common-envs" . | nindent 8 }}
          {{- include "georchestra.ldap-envs" . | nindent 8 }}
          {{- include "georchestra.database-georchestra-envs" . | nindent 8 }}
          {{- if $webapp.extra_environment }}
          {{- $webapp.extra_environment | toYaml | nindent 8 }}
          {{- end }}
        ports:
        - containerPort: 8080
          name: http-proxy
        volumeMounts:
          - mountPath: /etc/georchestra
            name: georchestra-datadir
        livenessProbe:
          httpGet:
            path: /_static/bootstrap_3.0.0/css/bootstrap-theme.min.css
            port: 8080
          periodSeconds: 10
          timeoutSeconds: 3
        startupProbe:
          tcpSocket:
            port: 8080
          failureThreshold: 5
          periodSeconds: 15
      {{- if $webapp.jetty_monitoring }}
      - name: jmx-collectd
        image: camptocamp/jmx-collectd:bullseye
        volumeMounts:
        - mountPath: /collectd-template
          name: georchestra-monitoring-cm
        ports:
        - containerPort: 9103
          name: prometheus
        command:
        - /bin/sh
        - -c
        - mkdir /etc/collectd/collectd.conf.d/ ;
          cat /collectd-template/collectd-jmx-jetty.conf | sed "s/localhost/$(hostname)/g" > /etc/collectd/collectd.conf.d/jmx.conf ;
          collectd -f
      {{- end }}
      volumes:
      - name: georchestra-datadir
        emptyDir: {}
      {{- if .Values.georchestra.datadir.git.ssh_secret }}
      - name: ssh-secret
        secret:
          secretName: {{ .Values.georchestra.datadir.git.ssh_secret }}
          defaultMode: 0400
      {{- end }}
      {{- if $webapp.jetty_monitoring }}
      - name: georchestra-monitoring-cm
        configMap:
          name: {{ include "georchestra.fullname" . }}-monitoring-cm
      {{- end }}
      {{- if $webapp.registry_secret }}
      imagePullSecrets:
      - name: {{ $webapp.registry_secret }}
      {{- end }}
{{- end }}
