{{- $webapp := .Values.georchestra.datadirsync -}}
{{- if $webapp.enabled -}}
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: {{ .Release.Namespace }}
  name: {{ include "georchestra.fullname" . }}-datadirsync-role
rules:
  - apiGroups: ["apps"]
    resources: ["pods", "replicasets", "deployments"]
    resourceNames:
      {{- $prefix := include "georchestra.fullname" . -}}
      {{- $deployments := list -}}
      {{- range $key, $values := $webapp.rolloutDeploymentsMapping }}
        {{- $deployments = concat $deployments $values }}
      {{- end }}
      {{- $deployments = mustUniq $deployments }}
      [{{- range $index, $item := $deployments }}
        {{- if $index }}, {{ end }}"{{ printf "%s-%s" $prefix $item }}"
      {{- end }}]
    verbs: ["get", "patch"]
{{- end }}
