{{- $webapp := .Values.georchestra.datadirsync  -}}
{{- if $webapp.enabled -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "georchestra.fullname" . }}-datadirsync-serviceaccount
  namespace: {{ .Release.Namespace }}
{{- end }}