{{- $webapp := .Values.georchestra.webapps.geonetwork.elasticsearch -}}
{{- if .Values.georchestra.webapps.geonetwork.enabled -}}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "georchestra.fullname" . }}-gn4-elasticsearch-svc
  labels:
    {{- include "georchestra.labels" . | nindent 4 }}
    app.kubernetes.io/component: {{ include "georchestra.fullname" . }}-gn4-elasticsearch
  {{- with $webapp.service.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  ports:
  - port: 9200
    protocol: TCP
    targetPort: 9200
  selector:
    org.georchestra.service/name: {{ include "georchestra.fullname" . }}-gn4-elasticsearch
{{- end }}