{{- $webapp := .Values.georchestra.webapps.geonetwork.elasticsearch -}}
{{- if and .Values.georchestra.webapps.geonetwork.enabled $webapp.enabled -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "georchestra.fullname" . }}-gn4-elasticsearch-secret
  labels:
    {{- include "georchestra.labels" . | nindent 4 }}
type: Opaque
data:
  password: {{ required ".Values.georchestra.webapps.geonetwork.elasticsearch.elasticPassword is required." $webapp.elasticPassword | b64enc | quote }}
{{- end }}
