{{- $webapp := .Values.cli -}}
{{- if $webapp.enabled -}}

apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "analytics.fullname" . }}-cli-config
  labels:
    {{- include "analytics.labels" . | nindent 4 }}
    app.kubernetes.io/component: {{ include "analytics.fullname" . }}-cli
data:
  cli.yaml: |
    database:
      drivername: "postgresql"
      host: !ENV "${TSDB_HOST:localhost}"
      port: !ENV "${TSDB_PORT:5433}"
      database: !ENV "${TSDB_NAME:analytics}"
      username: !ENV "${TSDB_USER:tsdb}"
      password: !ENV "${TSDB_PASSWORD:secret}"

    metrics:
      {{- toYaml $webapp.config.metrics | nindent 6 }}

    performance:
      {{- toYaml $webapp.config.performance | nindent 6 }}

    timezone: {{ $webapp.config.timezone | quote }}

    apps_mapping:
      {{- toYaml $webapp.config.appsMapping | nindent 6 }}

    parsers:
    {{- $webapp.config.parsers | nindent 6 }}

    logging:
      {{- toYaml $webapp.config.logging | nindent 6 }}
{{- end }}
