{{- if not .Values.timescaledb.auth.existingEnvSecret -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "analytics.fullname" . }}-timescaledb-env-secret
  labels:
    {{- include "analytics.labels" . | nindent 4 }}
    app.kubernetes.io/component: {{ include "analytics.fullname" . }}-timescaledb
type: Opaque
data:
  TSDB_OTEL_TABLE: {{ .Values.timescaledb.dbOpentelemetryTable | b64enc | quote }}
{{- end }}
