{{- if and (.Values.database.geodata) (not .Values.database.geodata.auth.existingSecret ) }}
{{- $database := .Values.database.geodata -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "georchestra.fullname" . }}-database-geodata-secret
  labels:
    {{- include "georchestra.labels" . | nindent 4 }}
type: Opaque
data:
  dbname: {{ required ".Values.geodata.auth.dbname is required." $database.auth.database | b64enc | quote }}
  host: {{ required ".Values.geodata.auth.host is required." $database.auth.host | b64enc | quote }}
  password: {{ required ".Values.geodata.auth.password is required." $database.auth.password | b64enc | quote }}
  port: {{ required ".Values.geodata.auth.port is required." $database.auth.port | b64enc | quote }}
  user: {{ required ".Values.geodata.auth.username is required." $database.auth.username | b64enc | quote }}
{{- end }}
