{{- $database := .Values.database -}}
{{- if not $database.auth.existingSecret -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "georchestra.fullname" . }}-database-georchestra-secret
  labels:
    {{- include "georchestra.labels" . | nindent 4 }}
type: Opaque
data:
  dbname: {{ required ".Values.database.auth.dbname is required." $database.auth.database | b64enc | quote }}
  {{- if $database.builtin }}
  host: {{ printf "%s-database" .Release.Name | b64enc | quote  }}
  {{- else }}
  host: {{ required ".Values.database.auth.host is required." $database.auth.host | b64enc | quote }}
  {{- end }}
  password: {{ required ".Values.database.auth.password is required." $database.auth.password | b64enc | quote |  }}
  port: {{ required ".Values.database.auth.port is required." $database.auth.port | b64enc | quote }}
  user: {{ required ".Values.database.auth.username is required." $database.auth.username | b64enc | quote }}
{{- end }}
