name: Lint and Test Charts

on:
  pull_request:
    paths-ignore:
      - "**/*.md"
      - "**/LICENCE"

jobs:
  lint-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Free Disk Space (Ubuntu)
        uses: jlumbroso/free-disk-space@main
        with:
          # this might remove tools that are actually needed,
          # if set to "true" but frees about 6 GB
          tool-cache: true
          # all of these default to true, but feel free to set to
          # "false" if necessary for your workflow
          android: true
          dotnet: true
          haskell: true
          large-packages: true
          docker-images: true
          swap-storage: false

      - name: Helm Installation
        uses: azure/setup-helm@v4

      - uses: actions/setup-python@main
        with:
          check-latest: true

      - name: Set up chart-testing
        uses: helm/chart-testing-action@main

      - name: Run chart-testing (lint)
        run: ct lint --validate-maintainers=false --chart-dirs . --target-branch ${{ github.event.repository.default_branch }}

      - name: Validate the Kubernetes manifest with yannh/kubeconform
        run: |
          helm plugin install https://github.com/jtyr/kubeconform-helm
          sudo pip install pyyaml
          for helmcharts in */; do
            helm kubeconform --summary "$helmcharts"
          done

      - name: k3s install + add more swap
        # chart testing do not work on main branch
        if: github.ref != '${{ github.event.repository.default_branch }}'
        run: |
          curl -sfL https://get.k3s.io | K3S_KUBECONFIG_MODE="644" sh -
          sudo dd if=/dev/zero of=/swapfile bs=1M count=8k status=progress
          sudo chmod 0600 /swapfile
          sudo mkswap /swapfile
          sudo swapon /swapfile
          free -h
          until KUBECONFIG=/etc/rancher/k3s/k3s.yaml kubectl get --raw='/readyz?verbose'; do echo "wait for k3s to finish"; done

      - name: Run chart-testing (install)
        # chart testing do not work on main branch
        if: github.ref != '${{ github.event.repository.default_branch }}'
        run: |
          KUBECONFIG=/etc/rancher/k3s/k3s.yaml ct install --chart-dirs . --helm-extra-args '--timeout 7200s' --skip-clean-up --target-branch ${{ github.event.repository.default_branch }}
