{{- $webapp := .Values.georchestra.webapps.proxy -}}
{{- if $webapp.enabled -}}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "georchestra.fullname" . }}-sp
  labels:
    {{- include "georchestra.labels" . | nindent 4 }}
    app.kubernetes.io/component: {{ include "georchestra.fullname" . }}-sp
spec:
  replicas: {{ $webapp.replicaCount }}
  selector:
    matchLabels:
      {{- include "georchestra.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: {{ include "georchestra.fullname" . }}-sp
  template:
    metadata:
      labels:
        {{- include "georchestra.selectorLabels" . | nindent 8 }}
        org.georchestra.service/name: {{ include "georchestra.fullname" . }}-sp
        app.kubernetes.io/component: {{ include "georchestra.fullname" . }}-sp
    spec:
      nodeSelector:
        "kubernetes.io/os": linux
        {{- with .Values.georchestra.nodeSelector }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
      initContainers:
      {{ include "georchestra.bootstrap_georchestra_datadir" . | nindent 6 }}
      {{- if $webapp.envsubst.enabled }}
      - name: envsubst
        image: "{{ .Values.tooling.envsubst.image.repository }}:{{ .Values.tooling.envsubst.image.tag }}"
        volumeMounts:
        - mountPath: /etc/georchestra
          name: georchestra-datadir
        env:
          - name: DEBUG
            value: "yes"
          - name: SUBST_FILES
            value: "/etc/georchestra/security-proxy/targets-mapping.properties"
          {{- include "georchestra.service-envs" . | nindent 10 }}
          {{- if $webapp.extra_environment }}
          {{- $webapp.extra_environment | toYaml | nindent 10 }}
          {{- end }}
      {{- end }}

      containers:
      - name: georchestra-sp
        image: {{ $webapp.docker_image }}
        imagePullPolicy: Always
        env:
          {{- include "georchestra.service-envs" . | nindent 10 }}
          {{- include "georchestra.common-envs" . | nindent 10 }}
          {{- include "georchestra.ldap-envs" . | nindent 10 }}
          {{- include "georchestra.database-georchestra-envs" . | nindent 10 }}
          {{- if $webapp.extra_environment }}
          {{- $webapp.extra_environment | toYaml | nindent 10 }}
          {{- end }}
        ports:
        - containerPort: 8080
          name: http-proxy
        volumeMounts:
          - mountPath: /etc/georchestra
            name: georchestra-datadir
        livenessProbe:
          httpGet:
            path: /_static/bootstrap_3.0.0/css/bootstrap-theme.min.css
            port: 8080
          periodSeconds: 10
          timeoutSeconds: 3
        startupProbe:
          tcpSocket:
            port: 8080
          failureThreshold: 5
          periodSeconds: 15
        resources:
          {{- toYaml $webapp.resources | nindent 10 }}
      volumes:
      - name: georchestra-datadir
        emptyDir: {}
      {{- if .Values.georchestra.datadir.git.ssh_secret }}
      - name: ssh-secret
        secret:
          secretName: {{ .Values.georchestra.datadir.git.ssh_secret }}
          defaultMode: 0400
      {{- end }}
      {{- if $webapp.registry_secret }}
      imagePullSecrets:
      - name: {{ $webapp.registry_secret }}
      {{- end }}
      {{- if $webapp.tolerations }}
      tolerations:
        {{- $webapp.tolerations | toYaml | nindent 8 }}
      {{- end }}
      {{- if .Values.hostAliases }}
      hostAliases:
        {{- .Values.hostAliases | toYaml | nindent 8 }}
      {{- end }}
{{- end }}
